extends:
  - ./web/core/.stylelintrc.json
  - stylelint-config-standard-scss

rules:
  at-rule-no-unknown: [true, {
    "ignoreAtRules": ["function", "if", "each", "include", "mixin"]
  }]
  color-no-invalid-hex: true
  string-quotes: "single"
  unit-allowed-list: ["px", "fr", "em", "rem", "%", "s", "deg", "vw", "vh"]
  order/order: []
  order/properties-order: []
  scss/at-import-partial-extension: [null]
  selector-class-pattern: null
  selector-id-pattern: null
  property-no-unknown: null
  no-descending-specificity: null
  scss/at-mixin-pattern: null