_core:
  default_config_hash: IgOVnECx6lbVt6JVFnadoEEugneDf3UblPZnOzov43Q
mode: simple
ignored_config_entities:
  - advagg.settings
  - advagg_css_minify.settings
  - advagg_js_minify.settings
  - 'backup_migrate.*'
  - checklistapi.progress.seo_checklist
  - config_ignore.settings
  - core.extension
  - 'metatag.*'
  - robotstxt.settings
  - security_review.settings
