_core:
  default_config_hash: PpB_t3-mnEd5Lckhxc9rfquSMa0CndPslGvJZlcg61E
langcode: en
bannerText: 'We use cookies on our website to give you the most relevant experience by remembering your preferences and repeat visits. By clicking “Accept All”, you consent to the use of ALL the cookies. However, you may visit "Cookie Settings" to provide a controlled consent.'
privacyPolicy: 'Privacy policy'
privacyUri: ''
imprint: Imprint
imprintUri: ''
cookieDocs: 'Cookie documentation'
cookieDocsUri: /cookies/documentation
officialWebsite: 'Official website'
denyAll: 'Deny all'
alwaysActive: 'Always active'
settings: 'Cookie settings'
acceptAll: 'Accept all'
requiredCookies: 'Required cookies'
cookieSettings: 'Cookie settings'
close: Close
readMore: 'Read more'
allowed: Allowed
denied: Denied
settingsAllServices: 'Settings for all services'
saveSettings: Save
default_langcode: en
disclaimerText: 'All cookie information is subject to change by the service providers. We update this information regularly.'
disclaimerTextPosition: above
processorDetailsLabel: 'Processor Company Details'
processorLabel: Company
processorWebsiteUrlLabel: 'Company Website'
processorPrivacyPolicyUrlLabel: 'Company Privacy Policy'
processorCookiePolicyUrlLabel: 'Company Cookie Policy'
processorContactLabel: 'Data Protection Contact Details'
placeholderAcceptAllText: 'Accept All Cookies'
