_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  webform_clientside_validation: -1
  admin_toolbar: 0
  admin_toolbar_tools: 0
  advagg: 0
  advagg_bundler: 0
  advagg_ext_minify: 0
  advagg_js_minify: 0
  advagg_validator: 0
  announcements_feed: 0
  autocomplete_deluxe: 0
  automated_cron: 0
  backup_migrate: 0
  backup_migrate_aws_s3: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layout_builder: 0
  bootstrap_styles: 0
  breakpoint: 0
  ces_pages: 0
  checklistapi: 0
  ckeditor5: 0
  clientside_validation: 0
  clientside_validation_jquery: 0
  color_field: 0
  comment: 0
  config: 0
  config_ignore: 0
  config_translation: 0
  contact: 0
  contextual: 0
  cookies: 0
  custom_layouts: 0
  datetime: 0
  dblog: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  encrypt: 0
  entity_clone: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  freshteam: 0
  gin_toolbar: 0
  help: 0
  history: 0
  image: 0
  inline_form_errors: 0
  key: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  link_attributes: 0
  link_attributes_menu_link_content: 0
  locale: 0
  mailsystem: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_app_links: 0
  metatag_dc: 0
  metatag_dc_advanced: 0
  metatag_facebook: 0
  metatag_favicons: 0
  metatag_google_cse: 0
  metatag_hreflang: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  metatag_open_graph_products: 0
  metatag_verification: 0
  metatag_views: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  real_aes: 0
  recaptcha_element: 0
  redirect: 0
  redirect_404: 0
  redirect_domain: 0
  redis: 0
  robotstxt: 0
  s3fs: 0
  search: 0
  seckit: 0
  security_review: 0
  sendgrid_integration: 0
  seo_checklist: 0
  shortcut: 0
  simplelogin: 0
  smtp: 0
  standard: 0
  statistics: 0
  superfish: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  tfa: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  user_redirect: 0
  views_autosubmit: 0
  views_infinite_scroll: 0
  views_ui: 0
  visitors: 0
  webform: 0
  webform_cards: 0
  webform_options_custom: 0
  webform_spam_words: 0
  webform_ui: 0
  webform_views: 0
  xmlsitemap_custom: 0
  xmlsitemap_engines: 0
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
theme:
  olivero: 0
  claro: 0
  gin: 0
  ces: 0
profile: standard
