_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: gin
defaults:
  sender: SMTPMailSystem
  formatter: SMTPMailSystem
modules:
  sendgrid_integration: {  }
  smtp:
    none:
      sender: SMTPMailSystem
      formatter: SMTPMailSystem
