_core:
  default_config_hash: VV0HFGFvi0Pou7lakptNvL-oNLy6iIUp5m6b6gf4xos
credentials_file: ''
bucket: ''
region: us-west-1
use_cname: true
domain_root: none
use_customhost: false
hostname: ''
domain: assets.codeenginestudio.com
use_path_style_endpoint: false
disable_version_sync: false
cache_control_header: ''
encryption: ''
use_https: false
ignore_cache: false
read_only: false
disable_cert_verify: false
redirect_styles_ttl: 0
root_folder: ''
public_folder: s3fs-public
private_folder: s3fs-private
presigned_urls: ''
saveas: ''
torrents: ''
use_cssjs_host: false
cssjs_host: ''
use_credentials_cache: false
credentials_cache_dir: ''
keymodule:
  secret_key_name: s3_secret_key
  access_key_name: s3_access_key
disable_shared_config_files: false
