login:
  reviewer:
    redirect_url: /
    weight: '-10'
  administrator:
    redirect_url: /
    weight: '-10'
  authenticated:
    redirect_url: /
    weight: '-10'
  content_editor:
    redirect_url: /
    weight: '-10'
logout:
  reviewer:
    redirect_url: /user/login
    weight: '-10'
  administrator:
    redirect_url: /user/login
    weight: '-10'
  authenticated:
    redirect_url: /user/login
    weight: '-10'
  content_editor:
    redirect_url: /user/login
    weight: '-10'
